package minor_project;

import com.sun.source.tree.BreakTree;
import com.sun.source.tree.Tree;
import java.awt.event.KeyEvent;
import java.lang.System.Logger;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Properties;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jitender
 */
public class newuser extends javax.swing.JFrame {

    int lastid;
    int last;
String otp;
    /**
     * Creates new form newuser
     */
    public newuser() {
        initComponents();
        getlastid();

        //getlast();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        demo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextname = new javax.swing.JTextField();
        jTextmail = new javax.swing.JTextField();
        jcontact = new javax.swing.JTextField();
        jTextlast = new javax.swing.JTextField();
        jTextpassword = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jradio1 = new javax.swing.JRadioButton();
        jRadio2 = new javax.swing.JRadioButton();
        jcal = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jstate = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jdistrict = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jadd = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jpin = new javax.swing.JTextField();
        val = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jotp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jo = new javax.swing.JTextField();
        jid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Online Gas Connection");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 640, 60));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButton6.setBackground(new java.awt.Color(255, 204, 51));
        jButton6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 882, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 60));

        demo.setBackground(new java.awt.Color(255, 51, 51));
        demo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("First Name");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-Mail");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact");

        jTextname.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N

        jTextmail.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jTextmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextmailKeyReleased(evt);
            }
        });

        jcontact.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcontactActionPerformed(evt);
            }
        });
        jcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcontactKeyPressed(evt);
            }
        });

        jTextlast.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N

        jTextpassword.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Submit");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        gender.add(jradio1);
        jradio1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jradio1.setForeground(new java.awt.Color(255, 255, 255));
        jradio1.setText("Male");

        gender.add(jRadio2);
        jRadio2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jRadio2.setForeground(new java.awt.Color(255, 255, 255));
        jRadio2.setText("Female");
        jRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio2ActionPerformed(evt);
            }
        });

        jcal.setBackground(new java.awt.Color(0, 0, 0));
        jcal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Date of Birth");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("User ID");

        juser.setEditable(false);
        juser.setBackground(new java.awt.Color(255, 255, 255));
        juser.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Sign Up");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("District");

        jstate.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Haryana", "Punjab", "Uttar Pardesh", "Rajasthan" }));
        jstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstateActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("State");

        jdistrict.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Address");

        jadd.setColumns(20);
        jadd.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jadd.setRows(5);
        jScrollPane2.setViewportView(jadd);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PIN Code");

        jpin.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpinKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Enter OTP");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Verify OTP");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout demoLayout = new javax.swing.GroupLayout(demo);
        demo.setLayout(demoLayout);
        demoLayout.setHorizontalGroup(
            demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoLayout.createSequentialGroup()
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(demoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addGroup(demoLayout.createSequentialGroup()
                                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(demoLayout.createSequentialGroup()
                                        .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                                        .addGap(76, 76, 76))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, demoLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)))
                                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jpin)
                                        .addComponent(jdistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jstate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcontact)
                                        .addComponent(jcal, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(juser, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextname, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextlast, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, demoLayout.createSequentialGroup()
                                            .addComponent(jradio1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadio2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jotp, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(demoLayout.createSequentialGroup()
                                        .addComponent(jTextmail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(val, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(demoLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(demoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        demoLayout.setVerticalGroup(
            demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(juser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(demoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextlast, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradio1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(demoLayout.createSequentialGroup()
                        .addComponent(jcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jstate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demoLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jotp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(155, Short.MAX_VALUE))
                    .addGroup(demoLayout.createSequentialGroup()
                        .addComponent(jpin)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(demoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(val, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(394, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(demo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 750, 570));

        jo.setText("0");
        getContentPane().add(jo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 0, 0));

        jid.setEditable(false);
        getContentPane().add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 325, 50, 40));

        jLabel15.setBackground(new java.awt.Color(51, 255, 255));
        jLabel15.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor_project/red1.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1000, 1080));

        setSize(new java.awt.Dimension(1009, 712));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void otpgenerte(){
         Random rand=new Random();
         otp=String.valueOf(rand.nextInt(999999));
        
        
                String email=jTextmail.getText();
                String message = "your otp is :- "+otp;
		String subject = "LPG Gas Pipe Connection";
		String to = email;
		String from = "anuj9896388147@gmail.com";
		
	sendEmail(message,subject,to,from);
//		sendAttach(message,subject,to,from);
	}

	//this is responsible to send the message with attachment
	private static void sendEmail(String message, String subject, String to, String from) {

		//Variable for gmail
		String host="smtp.gmail.com";
		
		//get the system properties
		Properties properties = System.getProperties();
		System.out.println("PROPERTIES "+properties);
		
		//setting important information to properties object
		
		//host set
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port","465");
		properties.put("mail.smtp.ssl.enable","true");
		properties.put("mail.smtp.auth","true");
		
		//Step 1: to get the session object..
		Session session=Session.getInstance(properties, new Authenticator() {
			@Override
			protected PasswordAuthentication getPasswordAuthentication() {				
				return new PasswordAuthentication("anuj9896388147@gmail.com","zdkpfmdqwzhxstkg");
			}			
		});
		
		session.setDebug(true);
		
		//Step 2 : compose the message [text,multi media]
		MimeMessage m = new MimeMessage(session);
		
		try {
		
		//from email
		m.setFrom(from);
		
		//adding recipient to message
		m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
		
		//adding subject to message
		m.setSubject(subject);
		m.setText(message);
		
		//step 3 
		Transport.send(m);
		System.out.println("send sucessfully .................");
		
		
		}catch (Exception e) {
			e.printStackTrace();
		}
    }
//============0000000000000000000000000000000000000009999999999999999999999999999999999999999999999999999999999
         public void welcome_update(){
                String email=jTextmail.getText();
                String message = "Thanks for register on LPG Natural Gas pipe line\n"
                        + "We are providing the best natural gas service";
		String subject = "LPG Gas Pipe Connection";
		String to = email;
		String from = "anuj9896388147@gmail.com";
		
	sendemail(message,subject,to,from);
//		sendAttach(message,subject,to,from);
	}

	//this is responsible to send the message with attachment
	private static void sendemail(String message, String subject, String to, String from) {

		//Variable for gmail
		String host="smtp.gmail.com";
		
		//get the system properties
		Properties properties = System.getProperties();
		System.out.println("PROPERTIES "+properties);
		
		//setting important information to properties object
		
		//host set
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port","465");
		properties.put("mail.smtp.ssl.enable","true");
		properties.put("mail.smtp.auth","true");
		
		//Step 1: to get the session object..
		Session session=Session.getInstance(properties, new Authenticator() {
			@Override
			protected PasswordAuthentication getPasswordAuthentication() {				
				return new PasswordAuthentication("anuj9896388147@gmail.com","zdkpfmdqwzhxstkg");
			}			
		});
		
		session.setDebug(true);
		
		//Step 2 : compose the message [text,multi media]
		MimeMessage m = new MimeMessage(session);
		
		try {
		
		//from email
		m.setFrom(from);
		
		//adding recipient to message
		m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
		
		//adding subject to message
		m.setSubject(subject);
		m.setText(message);
		
		//step 3 
		Transport.send(m);
		System.out.println("send sucessfully .................");
		
		
		}catch (Exception e) {
			e.printStackTrace();
		}
    }
        
        
        
        
    public void nul() {
        jTextname.setText(null);
        jTextlast.setText(null);
        jradio1.isSelected();
        jRadio2.isSelected();
        jcal.setCalendar(null);
        jcontact.setText(null);
        jdistrict.setSelectedItem(null);
        jstate.setSelectedItem(null);
        jpin.setText(null);
        jadd.setText(null);
        jTextmail.setText(null);
        jTextpassword.setText(null);
        jotp.setText(null);
    }

    public void getlastid() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gasconnection", "root", "Anuj0806$");
            String sql = "select max(id) from newuser";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                lastid = rs.getInt(1);
                lastid++;
                juser.setText(Integer.toString(lastid));

            } else {

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        anuj ad = new anuj();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpinKeyPressed
        String pin = jpin.getText();
        //set length of the string
        int length = pin.length();
        char c = evt.getKeyChar();
        //check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            //check for length of number is not greater than 10 digits
            if (length < 6) {
                jpin.setEditable(true);
            } else {
                //not editr if length is more than 10 digit
                jpin.setEditable(false);
            }
        } else {
            //now allow for key back space and delete
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                //allow edit
                jpin.setEditable(true);
            } else {
                jpin.setEditable(false);
            }
        }
    }//GEN-LAST:event_jpinKeyPressed

    private void jstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstateActionPerformed
        try {
            if (jstate.getSelectedItem().equals("Haryana")) {
                jdistrict.removeAllItems();
                jdistrict.addItem("Sonipat");
                jdistrict.addItem("Panipat");
                jdistrict.addItem("Sirsa");
                jdistrict.addItem("Karnal");
                jdistrict.addItem("Jind");
                jdistrict.addItem("Hisar");
                jdistrict.addItem("Rewari");
                jdistrict.addItem("Rohtat");
                //jdistrict.setSelectedItem(null);
            } else if (jstate.getSelectedItem().equals("Punjab")) {
                jdistrict.removeAllItems();
                jdistrict.addItem("Amritsar");
                jdistrict.addItem("Faridkot");
                jdistrict.addItem("Fazilka");
                jdistrict.addItem("Ferozepur.");
                jdistrict.addItem("Gurdaspur");
                jdistrict.addItem("Barnala");
                jdistrict.addItem("Fatehgarh Sahib");
                //jdistrict.setSelectedItem(null);
            } else if (jstate.getSelectedItem().equals("Uttar Pardesh")) {
                jdistrict.removeAllItems();
                jdistrict.addItem("Agra");
                jdistrict.addItem("Aligarh");
                jdistrict.addItem("Allahabad");
                jdistrict.addItem("Ambedkar Nagar");
                jdistrict.addItem("Amethi");
                jdistrict.addItem("Azamgarh");
                jdistrict.addItem("Mirzapur");
                jdistrict.addItem("Meerut");
                //jdistrict.setSelectedItem(null);
            } else if (jstate.getSelectedItem().equals("Rajasthan")) {
                jdistrict.removeAllItems();
                jdistrict.addItem("Ajmer");
                jdistrict.addItem("Bikaner");
                jdistrict.addItem("Kota");
                jdistrict.addItem("Jodhpur");
                jdistrict.addItem("Jaipur");
                jdistrict.addItem("Pali");
                jdistrict.addItem("Udaipur");
                jdistrict.addItem("Pratapgarh");
                //jdistrict.setSelectedItem(null);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jstateActionPerformed

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserActionPerformed

    private void jRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        nul();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

         String name = jTextname.getText();
        String last = jTextlast.getText();
        String radio = jradio1.getText();
        String contact = jcontact.getText();
        String pin = jpin.getText();
        String adderss = jadd.getText();
        String mail = jTextmail.getText();
        String pass = jTextpassword.getText();
        String set1 = val.getText();

        if ("".equals(name) || "".equals(last) || "".equals(radio) || "".equals(contact) || "".equals(pin) || "".equals(adderss) || "".equals(mail) || "".equals(pass)) {
            JOptionPane.showConfirmDialog(this, "All fields are Mandotory");
        }
        else if (set1 != null) {
            JOptionPane.showConfirmDialog(this, "enter a valid email");
        } 
        else {
       otpgenerte();       
        JOptionPane.showMessageDialog(null, "otp is send succesfully on your register email");
           
        }       
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcontactKeyPressed
        // TODO add your handling code here:
        String phoneNumber = jcontact.getText();
        //set length of the string
        int length = phoneNumber.length();
        char c = evt.getKeyChar();
        //check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            //check for length of number is not greater than 10 digits
            if (length < 10) {
                jcontact.setEditable(true);
            } else {
                //not editr if length is more than 10 digit
                jcontact.setEditable(false);
            }
        } else {
            //now allow for key back space and delete
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                //allow edit
                jcontact.setEditable(true);
            } else {
                jcontact.setEditable(false);
            }
        }
    }//GEN-LAST:event_jcontactKeyPressed

    private void jcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcontactActionPerformed


    }//GEN-LAST:event_jcontactActionPerformed

    private void jTextmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextmailKeyReleased
        String pat = "^[a-zA-Z0-9]{2,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(pat);
        Matcher match = patt.matcher(jTextmail.getText());
        if (!match.matches()) {
            val.setText("enter email is wrong");
        } else {
            val.setText(null);
        }
    }//GEN-LAST:event_jTextmailKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//         String name = jTextname.getText();
//        String last = jTextlast.getText();
//        String radio = jradio1.getText();
//        String contact = jcontact.getText();
//        String pin = jpin.getText();
//        String adderss = jadd.getText();
//        String mail = jTextmail.getText();
//        String pass = jTextpassword.getText();
//        String set1 = val.getText();
 String val=jotp.getText();
if("".equals(val)){
         JOptionPane.showMessageDialog(null, "You have not enter otp");
}
else{
    if(val.endsWith(otp))
        {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gasconnection", "root", "Anuj0806$");
                String sql = "insert into newuser values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                String Date = new SimpleDateFormat("yyyy_MM_dd").format(Calendar.getInstance().getTime());
                PreparedStatement ptst = conn.prepareStatement(sql);
                ptst.setString(1, String.valueOf(juser.getText()));
                ptst.setString(2, jTextname.getText());
                ptst.setString(3, jTextlast.getText());
                String dept = null;
                if (jradio1.isSelected()) {
                    dept = jradio1.getText();
                }
                if (jRadio2.isSelected()) {
                    dept = jRadio2.getText();
                }
                ptst.setString(4, dept);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(jcal.getDate());
                ptst.setString(5, date);
                ptst.setString(6, jcontact.getText());
                ptst.setString(7, (String) jstate.getSelectedItem());
                ptst.setString(8, (String) jdistrict.getSelectedItem());
                ptst.setString(9, jpin.getText());
                ptst.setString(10, jadd.getText());
                ptst.setString(11, jTextmail.getText());
                ptst.setString(12, jTextpassword.getText());
                ptst.setString(13, Date);
                ptst.setString(14, jo.getText());
                ptst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Account create succesfully");
                conn.close();
                welcome_update();
                anuj ad = new anuj();
                ad.setVisible(true);
                dispose();
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Your email is already register in our system");
                nul();
            }

            //************************************************************************************************************************
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gasconnection", "root", "Anuj0806$");
                String sql = "insert into login values(?,?,?)";
                PreparedStatement ptst = conn.prepareStatement(sql);
                ptst.setString(1, String.valueOf(juser.getText()));
                ptst.setString(2, jTextmail.getText());
                ptst.setString(3, jTextpassword.getText());
                ptst.executeUpdate();

            } catch (Exception e) {
                e.printStackTrace();
            }
  
        }
            else{ 
            JOptionPane.showMessageDialog(null, "wrong otp");
            jotp.setText(null);
        }
             
}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel demo;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadio2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextlast;
    private javax.swing.JTextField jTextmail;
    private javax.swing.JTextField jTextname;
    private javax.swing.JPasswordField jTextpassword;
    private javax.swing.JTextArea jadd;
    private com.toedter.calendar.JDateChooser jcal;
    private javax.swing.JTextField jcontact;
    private javax.swing.JComboBox<String> jdistrict;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jo;
    private javax.swing.JTextField jotp;
    private javax.swing.JTextField jpin;
    private javax.swing.JRadioButton jradio1;
    private javax.swing.JComboBox<String> jstate;
    private javax.swing.JTextField juser;
    private javax.swing.JLabel val;
    // End of variables declaration//GEN-END:variables

}
